### PR TITLE
Automatically find MSBuild of VS2017

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by slozier** [comment]
Close and reopen to test.

**Comment by slide** [comment]
Isn't this already in your other PR? https://github.com/IronLanguages/ironpython2/commit/26b2bd0d786f3dbdcf2a021ae258766a96575ed4

**Comment by slozier** [comment]
Oops, must have added it by accident in the other PR.

**Comment by slide** [comment]
I'm fine with doing it as part of the other PR if you want.

**Comment by slozier** [comment]
Alright, will close this one and add the other makefile fixes there.

**Pull request closed without merging**
