### PR TITLE
Fix #381

### LINKED ISSUE #381: `pip` should work after installation without needing to run `ipy -m ensurepip`
CPython Windows (and OSX) installers invoke `ensurepip` automatically as explained in [PEP-477](https://www.python.org/dev/peps/pep-0477/). IronPython Windows installer should do the same.

### PR DESCRIPTION
**Pull request by slide**
Add a feature for pip (selected by default) which will run ensurepip after files are copied. The uninstall will also run the ensurepip._uninstall.

### CODE REVIEW

**Comment by slozier** [comment]
I'm sure I've asked this before. Can't we pull WiX from NuGet?

**Comment by slide** [comment]
We could, yes. I don't see why it would be that much better right now though.

**Comment by slozier** [comment]
Would keep the size of the repo down. For example, if I download the source for this PR, it's an 5MB of (compressed) data.

**Comment by slide** [comment]
It wouldn't help for cloning since even if you delete the item, its still in the history. We'd have to delete from the history as well.

**Comment by slozier** [comment]
Yes it would help with cloning. When cloning you're basically downloading the full history, so we're downloading what's in there right now and then a second copy of the binaries from the updates in this PR.

**Pull request closed without merging**
