### PR TITLE
Fix #381

### LINKED ISSUE #381: `pip` should work after installation without needing to run `ipy -m ensurepip`
CPython Windows (and OSX) installers invoke `ensurepip` automatically as explained in [PEP-477](https://www.python.org/dev/peps/pep-0477/). IronPython Windows installer should do the same.

### PR DESCRIPTION
**Pull request by slide**
Add run of `ensurepip` to end of the installer

### CODE REVIEW

**Comment by slozier** [comment]
Did you change the install folder on purpose? Won't it break VS integration?

**Comment by slide** [comment]
No, I did not. That was something I didn't mean to commit. Good thing for reviews!

**Comment by slozier** [comment]
Is it easy to make the ensurepip optional (but selected by default) in the installer?

**Comment by slide** [comment]
Right now we don't have any component selection at all, so we would have to add that, which is not trivial as far as I remember.

**Comment by slozier** [comment]
Alright. Something wrong with my installer. I'm stuck in a broken state (can't install or uninstall). Will have to look at it some more tomorrow.

**Pull request closed without merging**
