### PR TITLE
Support for .Net Standard

### PR DESCRIPTION
**Pull request by YairHalberstadt**
I think this PR will need someone to review the places where I've decided to, or not to, make compilation conditional on NETSTANDARD2_0 being, or not being, defined. All the cases where I've made compilation conditional will be visible in the PR. However of the cases where I haven't made any changes, the one I am least sure about is IronPython.Runtime.Types.DocBuilder.cs line 576.

### CODE REVIEW

**Comment by slozier** [comment]
@YairHalberstadt I would probably exclude it in DocBuilder as well since having .NET Framework documentation doesn't necessarily make sense using .NET Standard assemblies, however I'm not too worried about it. Most users don't even have the reference assemblies installed on the computers.

**Comment by YairHalberstadt** [comment]
I've changed DocBuilder now

**Comment by YairHalberstadt** [comment]
I've now tested creating a nuget package on alocal feed, and using it to run python plugins from a .Net Standard project in our companies main solution. Everything works as expected.

**Comment by slozier** [comment]
Great, thanks for the PR!

**Comment by YairHalberstadt** [comment]
Is it possible to deploy a new budget package with these changes please?

**Comment by slozier** [comment]
My only concern at this point (well, other than figuring out how to do a release) is the prerelease package dependency which produces the following warning:
> EXEC : warning : Issue found with package 'DynamicLanguageRuntime'.
EXEC : warning : Issue: Prerelease dependency in stable package.
EXEC : warning : Description: A stable release of a package should not have a prerelease dependency.
EXEC : warning : Solution: Either modify the version spec of dependency "System.Reflection.Emit [4.6.0-preview.19073.11, )" or update the version field in the nuspec.

Can this cause issues to people trying to consume the package?

**Comment by YairHalberstadt** [comment]
I don't believe so, but it could be published as a prerelease package.

**Comment by YairHalberstadt** [comment]
Which might be a good idea anyway, as it will give a chance to see if any issues occur in wild.

**Comment by slozier** [comment]
I was thinking about that, but then we'd be stuck in prerelease mode until the stable RefEmit is released (alongside .NET Core 3.0 I assume). Not really an issue I guess since historically IronPython has been quite slow to release.

**Comment by YairHalberstadt** [comment]
Alternatively we could use the stable versions of the reflection.Emit package. Everything *should hopefully* work, but the error message when used on AOT would be less helpful.

**Pull request merged**
