### PR TITLE
Fix .NET 6.0 issues

### PR DESCRIPTION
**Pull request by slozier**
Resolves https://github.com/IronLanguages/ironpython2/issues/802

### CODE REVIEW

**Comment by sopelt** [comment]
Hi @slozier, did any more net6 issues come up and are there plans to ship this?
Thanks!

**Comment by slozier** [comment]
@sopelt I started prepping the release and December but never got around to doing the final testing. Hopefully I can get this out this week.

**Comment by sopelt** [comment]
Thank you for your work. We are looking forward to the update.

**Comment by slozier** [comment]
@sopelt 2.7.12 is now available.

**Comment by sopelt** [comment]
Thank you for your work @slozier ! I'll give it a try in the coming days.

**Pull request merged**
